apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:sts::615858357060:assumed-role/voclabs/user1884696=6897a8ee-9afd-11ec-903a-9715669c9ef3
      username: user1884696
      groups:
        - system:masters
