apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::615858357060:user/github-action-user
      username: github-action-user
      groups:
        - system:masters
